include:
  - project: 'e/os/releases'
    ref: master
    file: '/templates/.gitlab-ci.yml'

update-manifest-u:
  extends: .update-manifest

check-version:
  extends: .check-version

trigger-build-u-community:
  extends: .trigger-build-community
  variables:
    DEVICES: "FP4 tetris shiba"
    BUILD_BRANCH: "v1-u"

trigger-build-u-partner:
  extends: .trigger-build-partner
  variables:
    DEVICES: "FP4"
    BUILD_BRANCH: "v1-u"

trigger-build-u-official:
  extends: .trigger-build-official
  variables:
    DEVICES: "FP4 shiba"
    BUILD_BRANCH: "v1-u"
